version: "3"
services:
  postgres:
    image: postgres
    container_name: async_api_postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - async-api

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: async_api_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: async_api_kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REPLICA_FETCH_MAX_BYTES: 15048576
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 15048576
      KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 15048576
      CONNECT_PRODUCER_MAX_REQUEST_SIZE: 15048576
      CONNECT_CONSUMER_MAX_PARTITION_FETCH_BYTES: 15048576

networks:
  async-api:
